[env]
DATABASE_URL="postgres://nosso:verysecret@localhost/nosso_app_docker"
TEST_DATABASE_URL="postgres://nosso:verysecret@localhost/nosso_app_docker_test"
TEST_APP_DATABASE_URL="postgres://app_user:verysecret@localhost/nosso_app_docker_test"

JWT_SECRET="verysecret"

[build]
rustflags = ["--cfg", "tokio_unstable"]