[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = {version = "0.6", features = ["transport"]}
prost = "0.9"
prost-types = "0.9"

[build-dependencies]
prost-build = "0.9"
tonic-build = "0.6"
glob = "0.3.0"