# fly.toml file generated for services-dev on 2021-12-03T22:26:08Z

app = "nosso-services-dev"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
dockerfile = "Dockerfile.fly"

[env]
RUST_LOG="info"

[experimental]
  auto_rollback = true
  private_network = true

[[services]]
  internal_port = 50051

  [services.concurrency]
  hard_limit = 10180
  soft_limit = 10120
  type = "connections"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"