# fly.toml file generated for web-dev on 2021-12-03T19:15:24Z

app = "nosso-web-dev"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
SERVICES_URL="nosso-services-dev.internal:50051"
GRPC_NODE_TRACE="resolving_load_balancer,round_robin,keepalive"
GRPC_NODE_VERBOSITY="debug"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 10180
    soft_limit = 10120
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
